default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: angelo_souza
  password: 1234
  host: 127.0.0.1

development:
  <<: *default
  database: GatewayIntegration_development

test:
  <<: *default
  database: GatewayIntegration_test
